version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=desafio_innovation
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teste -d desafio_innovation"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=teste
      - DB_PASSWORD=1234
      - DB=desafio_innovation
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "yarn typeorm migration:run -d src/data-source && yarn dev"
volumes:
  pgdata:
